### PR TITLE
Gonzo/odsc wip

### PR DESCRIPTION
**Pull request by dgonzo**

### CODE REVIEW

**Comment by dgonzo** [comment]
@zmarkan, please review

**Comment by dgonzo** [comment]
@zmarkan @lindahaviland @peterklipfel between this codebase and the MLOps sessions I think we have the makings of a solid MLOps guide. It will probably be helpful to walk through this with you three.

**Comment by lindahaviland** [comment]
@dgonzo - okay I cloned it and yes, agree we should meet - for sure

**Comment by zmarkan** [comment]
Just saw this. I'll have a look at it today and come back with a few questions 👍

**Review by zmarkan — APPROVED** [review]

**Pull request merged**
